In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y=make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42) # Binary Classification Dataset

In [4]:
print("X:", X)
print("y:", y)

X: [[ 0.96479937 -0.06644898  0.98676805 ... -1.2101605  -0.62807677
   1.22727382]
 [-0.91651053 -0.56639459 -1.00861409 ... -0.98453405  0.36389642
   0.20947008]
 [-0.10948373 -0.43277388 -0.4576493  ... -0.2463834  -1.05814521
  -0.29737608]
 ...
 [ 1.67463306  1.75493307  1.58615382 ...  0.69272276 -1.50384972
   0.22526412]
 [-0.77860873 -0.83568901 -0.19484228 ... -0.49735437  2.47213818
   0.86718741]
 [ 0.24845351 -1.0034389   0.36046013 ...  0.77323999  0.1857344
   1.41641179]]
y: [0 1 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 1 1 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 0 0 0
 0 1 1 0 1 0 1 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 0 1 1 1 1 0 0 0 1 1 1 0 1 1
 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 0 0 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0
 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 1 0 1 1 0 0 1 1
 0 1 1 0 1 1 0 0 1 1 0 1 1 1 0 0 1 1 0 1 1 1 1 1 0 1 0 0 0 1 0 1 1 0 0 1 1
 0 0 1 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 1 1 0 0 1 0 1 0 1
 1 0 0 1 1 0 0 0 1 0 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 0 

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.30, random_state=42)

Logistic Regresssion Model

In [6]:
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [7]:
logistic.fit(X_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [8]:
y_pred=logistic.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0])

In [9]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [10]:
score=accuracy_score(y_test, y_pred)
print("Accuracy:", score)
cm=confusion_matrix(y_test, y_pred)
print("Confusion Matrix:", cm)
cr=classification_report(y_test, y_pred)
print("Classification Report:", cr)

Accuracy: 0.8466666666666667
Confusion Matrix: [[118  17]
 [ 29 136]]
Classification Report:               precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



Hyperparameter Tuning

In [11]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
penalty=['l1', 'l2', 'elasticnet']
c_values=[100, 10, 1.0, 0.1, 0.01]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [12]:
params = [
    {
        'penalty': ['l1'],
        'solver': ['liblinear', 'saga'],
        'C': c_values
    },
    {
        'penalty': ['l2'],
        'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
        'C': c_values
    },
    {
        'penalty': ['elasticnet'],
        'solver': ['saga'],
        'l1_ratio': [0.2, 0.5, 0.8],
        'C': c_values
    }
]

In [13]:
from sklearn.model_selection import GridSearchCV, StratifiedKFold
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [14]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model, param_grid=params, scoring='accuracy', cv=cv, n_jobs=-1)

In [15]:
grid

,estimator,LogisticRegression()
,param_grid,"[{'C': [100, 10, ...], 'penalty': ['l1'], 'solver': ['liblinear', 'saga']}, {'C': [100, 10, ...], 'penalty': ['l2'], 'solver': ['newton-cg', 'lbfgs', ...]}, ...]"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo... shuffle=True)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [16]:
grid.fit(X_train, y_train)

,estimator,LogisticRegression()
,param_grid,"[{'C': [100, 10, ...], 'penalty': ['l1'], 'solver': ['liblinear', 'saga']}, {'C': [100, 10, ...], 'penalty': ['l2'], 'solver': ['newton-cg', 'lbfgs', ...]}, ...]"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo... shuffle=True)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l1'


In [17]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [18]:
grid.best_score_

np.float64(0.8728571428571428)

In [19]:
y_pred=grid.predict(X_test)

In [20]:
score=accuracy_score(y_test, y_pred)
print("Accuracy:", score)
cm=confusion_matrix(y_test, y_pred)
print("Confusion Matrix:", cm)
cr=classification_report(y_test, y_pred)
print("Classification Report:", cr)

Accuracy: 0.8533333333333334
Confusion Matrix: [[123  12]
 [ 32 133]]
Classification Report:               precision    recall  f1-score   support

           0       0.79      0.91      0.85       135
           1       0.92      0.81      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



In [21]:
from sklearn.model_selection import RandomizedSearchCV
model=LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model, param_distributions=params, cv=5,scoring='accuracy')

In [22]:
randomcv.fit(X_train, y_train)

,estimator,LogisticRegression()
,param_distributions,"[{'C': [100, 10, ...], 'penalty': ['l1'], 'solver': ['liblinear', 'saga']}, {'C': [100, 10, ...], 'penalty': ['l2'], 'solver': ['newton-cg', 'lbfgs', ...]}, ...]"
,n_iter,10
,scoring,'accuracy'
,n_jobs,None
,refit,True
,cv,5
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [23]:
randomcv.best_score_

np.float64(0.8771428571428572)

In [24]:
randomcv.best_params_

{'solver': 'liblinear', 'penalty': 'l2', 'C': 0.01}

In [25]:
y_pred=randomcv.predict(X_test)

In [26]:
score=accuracy_score(y_test, y_pred)
print("Accuracy:", score)
cm=confusion_matrix(y_test, y_pred)
print("Confusion Matrix:", cm)
cr=classification_report(y_test, y_pred)
print("Classification Report:", cr)

Accuracy: 0.8533333333333334
Confusion Matrix: [[124  11]
 [ 33 132]]
Classification Report:               precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



MultiClass Classification

In [27]:
X,y=make_classification(n_samples=1000, n_features=10, n_informative=3, n_classes=3, random_state=42) # Binary Classification Dataset

In [28]:
X

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]], shape=(1000, 10))

In [29]:
y

array([1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1,
       2, 2, 1, 2, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1,
       2, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 2,
       0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0,
       0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 2, 1, 2, 1, 0, 2, 0, 0, 2, 1, 0, 2, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 1, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 2,
       1, 0, 2, 1, 2, 1, 2, 0, 1, 1, 0, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2,
       1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 2, 0,
       2, 0, 1, 1, 2, 1, 2, 2, 2, 2, 0, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1,
       0, 2, 0, 0, 1, 0, 2, 0, 1, 2, 2, 2, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 1,

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [31]:
from sklearn.linear_model import LogisticRegression
logistic= LogisticRegression(multi_class='ovr')
logistic.fit(X_train, y_train)
y_pred=logistic.predict(X_test)

c:\Users\jhash\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [32]:
y_pred

array([2, 0, 1, 2, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0,
       2, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 0, 2, 2, 2, 1, 0, 0, 1, 2, 0,
       1, 2, 1, 0, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1,
       0, 1, 0, 1, 0, 2, 2, 0, 0, 0, 2, 1, 1, 2, 2, 0, 2, 1, 0, 1, 1, 2,
       1, 1, 2, 2, 1, 2, 2, 2, 1, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 0, 2,
       0, 1, 2, 0, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 2, 0, 0, 1, 0, 2, 1, 0,
       2, 2, 2, 0, 0, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 0, 0, 1, 2, 0, 0, 2,
       1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 0, 0, 2,
       0, 1, 1, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 2, 2, 1, 2,
       0, 1, 2, 2, 1, 1, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 2, 0, 0, 2,
       0, 2, 0, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0, 1, 1, 0, 1, 2, 0, 2, 2,
       0, 0, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 0, 1, 0, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 1])

In [33]:
score=accuracy_score(y_test, y_pred)
print("Accuracy:", score)
cm=confusion_matrix(y_test, y_pred)
print("Confusion Matrix:", cm)
cr=classification_report(y_test, y_pred)
print("Classification Report:", cr)

Accuracy: 0.68
Confusion Matrix: [[79 16  8]
 [31 38 27]
 [ 3 11 87]]
Classification Report:               precision    recall  f1-score   support

           0       0.70      0.77      0.73       103
           1       0.58      0.40      0.47        96
           2       0.71      0.86      0.78       101

    accuracy                           0.68       300
   macro avg       0.67      0.67      0.66       300
weighted avg       0.67      0.68      0.66       300

